name: 'Generate Snake'
on:
  schedule:
      # every 6 hours
    #- cron: "0 */6 * * *"
    - cron: "* * * * *"

permissions:
  contents: read
  id-token: write
  pull-requests: write

  # schedule: # execute every 12 hours
  #   - cron: "* */12 * * *"
  #workflow_dispatch:
jobs:
  build:
    name: Jobs to Generate Snake
    runs-on: ubuntu-latest
    steps:
      # Snake Animation
      - uses: Platane/snk/svg-only@v3
        id: snake-gif
  
        with:
          github_user_name: guhus
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
            
      - uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          
