name: 'Generate Guhus Snake'
on:
  #Manually run when workflow_dispatch is active
  #workflow_dispatch:
  schedule:
    # every 6 hours
    - cron: "0 */6 * * *"
    #Every 5 minutes
    #- cron: '*/5 * * * *'

permissions:
  contents: read
  id-token: write
  pull-requests: write
  
jobs:
  build:
    name: Jobs to Generate Guhus Snake
    runs-on: ubuntu-latest
    steps:
      # Snake Animation
      - uses: Platane/snk/svg-only@v3
        id: snake-gif
        with:
          github_user_name: guhus
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
            
      - uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          
